<?php

class DBConstanst
{
    //order
    const ORDER_STATUS_PENDING = 0;
    const ORDER_STATUS_AR_APPROVED = 1;
    CONST ORDER_STATUS_PAYMENT_APPROVED = 2;
    const ORDER_STATUS_STOCK_AVAILABLE = 3;
    const ORDER_STATUS_STOCK_UNAVAILABLE = 4;
    const ORDER_STATUS_REQUESTED_TO_SUPPLIER = 5;
    const ORDER_STATUS_SENT_TO_CUSTOMER = 6;
    const ORDER_STATUS_REJECTED = 99;
    const ORDER_STATUS_CANCELED = 100;
    const ORDER_STATUS_INVOICED_PAYMENT_UNAPPROVED = 101;

}